### ISSUE TITLE
Gzip server responses (streaming)

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#1001]
From [ch2511](https://app.clubhouse.io/learnersguild/story/2511)

Companion chore to https://app.clubhouse.io/learnersguild/story/2420/gzip-server-responses-non-streaming.

Compress server responses sent via streams/events.

Rsources:
https://github.com/expressjs/compression#server-sent-events

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: move to P4 GH?

**Comment by prattsj** [comment]
Already done.
