### ISSUE TITLE
Set default phase to 1 for new learners

### ISSUE THREAD

**Issue by prattsj** [LearnersGuild/echo#1080]
Depends on:
- https://github.com/LearnersGuild/idm/issues/196
- https://github.com/LearnersGuild/echo/issues/1079

When a new member is created for a user with the `learner` role, automatically set their Phase to 1.

**Comment by deadlyicon** [comment]
MetalCanine
Maxmi
Framinus
jcelder
paradoxinversion
NeoJax
Mbalcorta
milestribble
tdump

**Comment by prattsj** [comment]
Thanks, @deadlyicon. Since these accounts have already been created, i'll set their phases manually.

**Comment by prattsj** [comment]
Fixed in https://github.com/LearnersGuild/echo/pull/1083.
