### ISSUE TITLE
Player DM'ed retrospective summary

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#355]
@shereefb commented on [Mon Aug 01 2016](https://github.com/LearnersGuild/learning-os-software/issues/163)

After every player on a project has completed the retrospective, the player should receive a DM in echo with the following information:

---

Depends on RocketChat/Rocket.Chat#358
Depends on RocketChat/Rocket.Chat#365

---

Retrospective results for [#happy-tiger](#):

**Feedback from your team:**
- Jeffrey, I like working with you because you shower every day and I'd like working with you even more if you chewed with your mouth closed.
- Jeffrey, I like working with you because you have an interesting way of deconstructing problems, and I'd like working with you even more if you took more risks.
- ...

**Stats earned from this project:**

| name | score |
| --- | --: |
| learning support | 70% |
| culture support | 84% |

**Contribution to the project:**

Your contribution to the project: 42%
Team size: 3
Expected contribution for team size: 33.33%
Relative contribution: +8.67%

| averaged | self-assessed | team-assessed |
| :-- | --: | --: |
| 42% | 40% | 45% |

**Hours contributed to this project:**

| player | num hours |
| --- | --: |
| @deadlyicon (Jared Grippe) | 5 |
| @jeffreywescott (Jeffrey Wescott) | 42 |
| @tannerwelsh (Tanner Welsh) | 34 |

**Comment by heyheyjp** [comment]
@jeffreywescott: Rocket.Chat doesn't support all of the Markdown features we get in GitHub-flavored markdown, including fancy table rendering. So, we can't easily deliver on something that looks like:

> | name | score |
> | --- | --: |
> | learning support | 70% |
> | culture support | 84% |

We'll need to come up with an alternative way to style the stats in the DMs.

Here's one suggestion, falling back to something similar to what we spec'd in https://github.com/LearnersGuild/game/issues/111:

```
Learning Support   [ 70%]
Culture Support    [ 84%]
```

Open Rocket.Chat issue:
https://github.com/RocketChat/feature-requests/issues/642

**Comment by tannerwelsh** [comment]
> @shereefb, @tannerwelsh: need design sign-off on RocketChat/Rocket.Chat#182 if we're going to deliver the Support stats in this message as spec'd in the description.

@shereefb all this needs is an 👍  from you (after I implemented changes to take hours into account)

**Comment by shereefb** [comment]
@tannerwelsh changing it from RocketChat/Rocket.Chat#182 because 
1. Score doesn't need to be weighted by hours or "recentness" since it only covers 1 project. 
2. Scores are from 1 to 7 so shifting them to 0 to 6 gives us the whole range of 0 to 100%.
