### ISSUE TITLE
Update Cycle launch message in Slack

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#933]
The list of project names has no value now that they don't link to project channels. We can remove it from this alert and replace it with a count and a link to the projects page in the echo web UI.

New messaging:

**🚀 Cycle <CYCLE_NUMBER> has been launched!**
> 44 projects were created.

For project details, visit https://echo.learnersguild.org/projects.

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: move to P4 GH?

**Comment by ian-deans** [comment]
Quick question about the wording in the new message, the current announcement displays the cycle number.
```js
`🚀  *Cycle ${cycle.cycleNumber} has been launched!*\n`
```
Should I change this to match the message in the issue? Or leave the cycle number in there.

**Comment by prattsj** [comment]
@ian-deans: updated. please include the number.
