### ISSUE TITLE
retros didn't get formed for cycle 49?

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#942]
From [ch3639](https://app.clubhouse.io/learnersguild/story/3639)

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @prattsj:]** Moved to github issue for work in P4:
https://github.com/LearnersGuild/echo/issues/908

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: should we archive this?

**Comment by prattsj** [comment]
Duplicate of #908.
