### ISSUE TITLE
user phase change handling/validation

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#943]
From [ch3429](https://app.clubhouse.io/learnersguild/story/3429)

- invite user to phase channel
- if cycle is already in `GOAL_SELECTION`, update voting pools if entering or leaving a voting phase.

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @prattsj:]** Moved to github issue for work in P4:
https://github.com/LearnersGuild/echo/issues/909

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: should we archive this?

**Comment by prattsj** [comment]
Duplicate of #909.
