### ISSUE TITLE
change UserForm phase input control to dropdown

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#944]
From [ch3333](https://app.clubhouse.io/learnersguild/story/3333)

currently a text input.

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @prattsj:]** Moved to github issue for work in P4:
https://github.com/LearnersGuild/echo/issues/910

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: should we archive this?

**Comment by prattsj** [comment]
Duplicate of #910.
