### ISSUE TITLE
/phases view

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#945]
From [ch2983](https://app.clubhouse.io/learnersguild/story/2983)

requested by LF, moderator roles:

- 1 tab per phase
- similar to `/projects` view, but each tab contains the list of learners *currently* in that phase

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @prattsj:]** Moved to github issue for P4 work:
https://github.com/LearnersGuild/echo/issues/911

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: should we archive this?

**Comment by prattsj** [comment]
Duplicate of #911.
