### ISSUE TITLE
Re-enable prism syntax highlighting in software guide

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#959]
From [ch3657](https://app.clubhouse.io/learnersguild/story/3657)

https://github.com/gaearon/gitbook-plugin-prism/issues/24

**Comment by prattsj** [comment]
Issue moved to [LearnersGuild/learning-os-software #169](https://github.com/LearnersGuild/learning-os-software/issues/169) via [**ZenHub**](https://www.zenhub.com/)
