### ISSUE TITLE
Introduce dataService queries

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#974]
From [ch1955](https://app.clubhouse.io/learnersguild/story/1955)

This was originally a task in story #1657.

---

We have a need for queries more complex than can be done with the standard get/insert/update/filter/etc Thinky model interface. 

Because the purpose of these queries is ultimately to only retrieve data from the `game` service's primary datastore (a rethinkdb DB), it makes sense for this logic to live inside/be exposed through the `dataService`. 

Another benefit of having these as functions exposed by the `dataService` (as opposed to being standalone server actions) is that they are easily distinguished as having an important property: that the promises returned from these functions are rethinkdb queries to which additional rethinkdb query methods can be chained.

These functions/modules will be located at `server/services/dataService/queries`.

**Comment by prattsj** [comment]
Already complete.
