### ISSUE TITLE
Cannot create new invite code associated with the `staff` role

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#986]
To repro:
1. Navigate to echo.learnersguild.org/chapters
2. Click on a chapter to edit it
3. Click the button to create a new invite code
4. Fill out the form, specifying `staff` as the associated role

**Expected results:** invite code created successfully
**Actual results:** invite code creation failed

---

From [ch1815](https://app.clubhouse.io/learnersguild/story/1815)

See attached screen shot:

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: screenshot missing? Not sure what this bug is.

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @prattsj:]** Hah. Sorry about that, @jeffreywescott. Basically, when I tried to create a code, it was validating the roles and `staff` wasn't one that was allowed.

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: move to P4 GH?

**Comment by prattsj** [comment]
@sdweber422: note that I'm not sure this is still an issue. Once https://github.com/LearnersGuild/idm/issues/186 is fixed, you might find that this now works. Let me know if you can't repro with the `staff` role, and we'll close this out.
