### ISSUE TITLE
cycle end/start announcements are out-of-order

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#989]
From [ch2096](https://app.clubhouse.io/learnersguild/story/2096)

**Expected:**
Announcement that cycle N has been completed followed by the announcement that cycle N+1 has started and voting is open.

**Actual:**
Announcement that voting has begun for cycle N+1 followed by announcement that cycle N has ended.

**Screencap:**
![31790eea-5033-11e6-811b-5a451fb705e2.png](https://clubhouse-assets.s3.amazonaws.com/586b24df-3b14-4cb6-b4b4-e78b31bf192e/58efef70-dd1e-49e1-bcdd-76d1fcfaaab8/31790eea-5033-11e6-811b-5a451fb705e2.png)

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: move to P4 GH?

**Comment by prattsj** [comment]
Fixed since switching to job queue for outbound slack messaging.
