### ISSUE TITLE
chapter names should enforce case-insensitive uniqueness

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#991]
From [ch354](https://app.clubhouse.io/learnersguild/story/354)

Possible to have two separate chapters named "Todton" and "todton".

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: move to P4 GH?

**Comment by prattsj** [comment]
Duplicate of https://github.com/LearnersGuild/echo/issues/987.
