### ISSUE TITLE
Infinite redirect loop w/ localtunnel for slack

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#996]
From [ch2187](https://app.clubhouse.io/learnersguild/story/2187)

When following directions in `game` README.

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** Can you give a bit more context here? I'm not seeing this on my setup. Redirect when you hit a URL in the browser? When you issue a command?

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: move to P4 GH?

**Comment by prattsj** [comment]
Directions updated in README.
